version: '3.8'
name: 'rinha-backend-quarkus'

services:
  api-1: &api
    image: rodriginhu/rinha-backend-quarkus:latest
    hostname: api-1
    environment:
      - QUARKUS_HTTP_PORT=8080
      - JAVA_TOOL_OPTIONS=-Xmx650m -XX:MaxRAMPercentage=75
    depends_on:
      postgres-db:
        condition: service_healthy
      cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '700M'
    network_mode: 'host'

  api-2:
    <<: *api
    hostname: api-2
    environment:
      - QUARKUS_HTTP_PORT=8081
      - JAVA_TOOL_OPTIONS=-Xmx650m -XX:MaxRAMPercentage=75

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '400M'
    network_mode: 'host'

  postgres-db:
    image: postgres:latest
    hostname: postgres-db
    command:
      'postgres -c max_connections=400 -c shared_buffers=512MB'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432 -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1150M'
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: 'host'

  cache:
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
    command: 'redis-server --save "" --appendonly no --maxclients 20000'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '50M'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    healthcheck:
      test: [ 'CMD', 'redis-cli', '--raw', 'incr', 'ping' ]
    network_mode: 'host'
